FROM ubuntu

RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get upgrade -y
RUN apt-get install -y nodejs

WORKDIR /home/app

RUN npm install -g yarn

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn install

COPY . .

ENTRYPOINT [ "yarn", "dev" ]